// Switchboard — lights-out toggle puzzle. Tapping a button flips it and its
// four orthogonal neighbours; switch every light off to clear the board.
// Puzzles are generated by scrambling an all-off board with K distinct taps,
// so every board is solvable in (at most) K taps — that K is the par.
import { createGameCanvas, palette, roundRect } from "../../engine/canvas";
import { makeHud, showOverlay } from "../../engine/ui";
import { toast, type Sdk } from "../../sdk/platform";

const ID = "switchboard";
const HINT_COST = 30;

// Level curve: grid grows every 2 levels (3×3 → 7×7 cap); scramble taps grow by 1 per level.
const gridSize = (level: number) => Math.min(7, 3 + Math.floor((level - 1) / 2));
const scrambleTaps = (level: number, n: number) => Math.min(n * n - 1, 2 + level);

interface Ripple {
  x: number;
  y: number;
  t: number;
}

export function mountSwitchboard(host: HTMLElement, sdk: Sdk): () => void {
  const hud = makeHud(host, ["Level", "Taps", "Par"]);
  const gc = createGameCanvas(host, 1.0);
  const { ctx } = gc;

  let level = sdk.getLevel(ID);
  let n = 3;
  let par = 0;
  let taps = 0;
  let lights: boolean[] = [];
  let startScramble: number[] = []; // the level's original scramble (for Reset / Try Again)
  let need = new Set<number>(); // cells still required to solve (scramble XOR player taps)
  let solved = false;
  let ripples: Ripple[] = [];
  let hintCell = -1;
  let hintT = 0;
  let finishTimer = 0;

  function toggle(i: number) {
    const x = i % n;
    const y = Math.floor(i / n);
    const cells: [number, number][] = [[x, y], [x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]];
    for (const [cx, cy] of cells) {
      if (cx >= 0 && cx < n && cy >= 0 && cy < n) lights[cy * n + cx] = !lights[cy * n + cx];
    }
  }

  // Apply the stored scramble to a fresh all-off board.
  function applyStart() {
    lights = new Array<boolean>(n * n).fill(false);
    need = new Set<number>();
    for (const i of startScramble) {
      toggle(i);
      need.add(i);
    }
    taps = 0;
    solved = false;
    ripples = [];
    hintCell = -1;
    hud.set("Level", level);
    hud.set("Taps", 0);
    hud.set("Par", par);
    hintBtn.style.display = level >= 4 ? "" : "none";
  }

  function newPuzzle() {
    level = sdk.getLevel(ID);
    n = gridSize(level);
    par = scrambleTaps(level, n);
    const pool = Array.from({ length: n * n }, (_, i) => i);
    for (let i = pool.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    startScramble = pool.slice(0, par);
    applyStart();
    // Rare case: the scramble cancels itself out to an all-off board — reroll.
    if (lights.every((l) => !l)) newPuzzle();
  }

  function finish() {
    const leveledUp = taps <= par + 3;
    if (leveledUp) {
      level += 1;
      sdk.setLevel(ID, level);
    }
    const coins = sdk.scaleReward(leveledUp ? 5 : 2, level);
    sdk.addCoins(coins, "Switchboard");
    const isBest = sdk.submitScore(ID, level);
    hud.set("Level", level);
    showOverlay(gc.canvas, {
      title: leveledUp ? "⬆️ Level Up!" : "Solved! 💡",
      subtitle: leveledUp
        ? `Level ${level} — more lights`
        : `${taps} taps · Solve in ≤ ${par + 3} taps to level up`,
      coins,
      isBest,
      mood: "win",
      primaryLabel: leveledUp ? "Next Level" : "Try Again",
      onPrimary: leveledUp ? newPuzzle : applyStart,
    });
  }

  gc.onDown((p) => {
    if (solved) return;
    const { pad, cell } = layout();
    const cx = Math.floor((p.x - pad) / cell);
    const cy = Math.floor((p.y - pad) / cell);
    if (cx < 0 || cx >= n || cy < 0 || cy >= n) return;
    const i = cy * n + cx;
    toggle(i);
    if (need.has(i)) need.delete(i);
    else need.add(i);
    if (i === hintCell) hintCell = -1;
    taps++;
    hud.set("Taps", taps);
    sdk.haptic();
    sdk.sfx("tick");
    ripples.push({ x: cx, y: cy, t: 0 });
    if (lights.every((l) => !l)) {
      solved = true;
      sdk.sfx("clear");
      finishTimer = window.setTimeout(finish, 450);
    }
  });

  // ── Controls: free Reset + paid Hint (from Level 4) ──
  const controls = document.createElement("div");
  controls.className = "game-controls";
  const resetBtn = document.createElement("button");
  resetBtn.className = "btn-ghost";
  resetBtn.textContent = "↺ Reset";
  resetBtn.addEventListener("click", () => !solved && applyStart());
  const hintBtn = document.createElement("button");
  hintBtn.className = "btn-ghost";
  hintBtn.textContent = `💡 Hint · ${HINT_COST} 🪙`;
  hintBtn.addEventListener("click", () => {
    if (solved || need.size === 0) return;
    if (!sdk.spendCoins(HINT_COST)) return toast("Not enough coins — visit the Shop 🛒");
    const opts = [...need];
    hintCell = opts[Math.floor(Math.random() * opts.length)];
    hintT = 0;
    sdk.sfx("click");
  });
  controls.append(resetBtn, hintBtn);
  host.appendChild(controls);

  function layout() {
    const pad = 14;
    return { pad, cell: (gc.w - pad * 2) / n };
  }

  gc.run((dt) => {
    ctx.clearRect(0, 0, gc.w, gc.h);
    roundRect(ctx, 0, 0, gc.w, gc.h, 18, palette.bg);
    const { pad, cell } = layout();
    ripples = ripples.filter((r) => (r.t += dt) < 0.6);
    if (hintCell >= 0 && (hintT += dt) > 3) hintCell = -1;

    for (let y = 0; y < n; y++) {
      for (let x = 0; x < n; x++) {
        const i = y * n + x;
        const cx = pad + x * cell + cell / 2;
        const cy = pad + y * cell + cell / 2;
        // Ripple: a pulse travelling outward (in cell units) from each tap.
        let bump = 0;
        for (const r of ripples) {
          const d = Math.hypot(x - r.x, y - r.y);
          const front = r.t * 8;
          bump += Math.max(0, 1 - Math.abs(front - d)) * (1 - r.t / 0.6);
        }
        const rad = cell * (0.36 + Math.min(0.08, bump * 0.08));
        roundRect(ctx, cx - cell / 2 + 3, cy - cell / 2 + 3, cell - 6, cell - 6, 10, "rgba(255,248,236,0.04)");
        ctx.save();
        ctx.beginPath();
        ctx.arc(cx, cy, rad, 0, Math.PI * 2);
        if (lights[i]) {
          const g = ctx.createRadialGradient(cx - rad * 0.3, cy - rad * 0.3, rad * 0.1, cx, cy, rad);
          g.addColorStop(0, "#fff6c9");
          g.addColorStop(0.5, "#ffd166");
          g.addColorStop(1, "#ff9f1c");
          ctx.shadowColor = "#ffcf33";
          ctx.shadowBlur = 22 + bump * 14;
          ctx.fillStyle = g;
        } else {
          ctx.fillStyle = "#3a3f5e";
        }
        ctx.fill();
        ctx.restore();
        ctx.lineWidth = 2;
        ctx.strokeStyle = lights[i] ? "rgba(255,243,196,0.9)" : "rgba(160,170,210,0.25)";
        ctx.stroke();
        if (i === hintCell && Math.floor(hintT * 4) % 2 === 0) {
          ctx.beginPath();
          ctx.arc(cx, cy, cell * 0.46, 0, Math.PI * 2);
          ctx.lineWidth = 4;
          ctx.strokeStyle = palette.teal;
          ctx.stroke();
        }
      }
    }
    // Expanding ring from the tapped button.
    for (const r of ripples) {
      ctx.beginPath();
      ctx.arc(pad + r.x * cell + cell / 2, pad + r.y * cell + cell / 2, cell * (0.4 + r.t * 3), 0, Math.PI * 2);
      ctx.lineWidth = 2;
      ctx.strokeStyle = `rgba(255,209,102,${0.5 * (1 - r.t / 0.6)})`;
      ctx.stroke();
    }
  });

  newPuzzle();
  return () => {
    clearTimeout(finishTimer);
    gc.destroy();
  };
}
